<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>FEBA531A-47BB-4C15-80E8-B239FD3CFBA4</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>&lt;%</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.section.embedded.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>source.euphoria.etml.embedded.html</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.euphoria</string>
                    </dict>
                </array>
                <key>end</key>
                <string>-?%&gt;</string>
            </dict>
            <dict>
                <key>include</key>
                <string>text.html.basic</string>
            </dict>
        </array>
        <key>name</key>
        <string>HTML (Euphoria)</string>
        <key>scopeName</key>
        <string>text.html.euphoria</string>
        <key>fileTypes</key>
        <array>
            <string>etml</string>
            <string>etag</string>
        </array>
        <key>foldingStopMarker</key>
        <string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
        <key>foldingStartMarker</key>
        <string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
    </dict>
</plist>
