<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>B44EEA00-8659-421B-BD7C-9015E45CB8ED</string>
        <key>keyEquivalent</key>
        <string>^~E</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>constant.numeric.standard.euphoria</string>
                <key>match</key>
                <string>\b[+-]?[0-9_]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.binary.euphoria</string>
                <key>match</key>
                <string>\b0b[0-1_]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.octal.euphoria</string>
                <key>match</key>
                <string>\b0t[0-7_]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.decimal.euphoria</string>
                <key>match</key>
                <string>\b0d[0-9_]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.hex.euphoria</string>
                <key>match</key>
                <string>\b0x[0-9A-Fa-f_]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.hex-old.euphoria</string>
                <key>match</key>
                <string>#[0-9A-Fa-f_]+\b</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>^\s*include\b</string>
                <key>name</key>
                <string>meta.preprocessor.include.euphoria</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.as.euphoria</string>
                        <key>match</key>
                        <string>\bas\b</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.quoted.filename.euphoria</string>
                        <key>match</key>
                        <string>\b[^ ]+\b</string>
                    </dict>
                </array>
                <key>end</key>
                <string>$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.quoted.namespace.euphoria</string>
                <key>match</key>
                <string>\b[a-zA-Z_][A-Za-z0-9_]*:</string>
            </dict>
            <dict>
                <key>name</key>
                <string>meta.preprocessor.euphoria</string>
                <key>match</key>
                <string>\b(end ifdef|elsifdef|elsedef|ifdef|namespace|trace|with|without)\b</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>keyword.control.euphoria</string>
                <key>match</key>
                <string>^\s*(deprecate\s+)?((override|global|public|export)\s+)?(function|procedure|type|routine)\s*([a-zA-Z_][a-zA-Z0-9_]*)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.euphoria</string>
                <key>match</key>
                <string>(?x)\b(
	         	and|as
    	     	|by
        	 	|case|constant
         		|deprecate|do
	         	|else|elsif|end|enum
	         	|for|function
	         	|if
	         	|loop
	         	|not
	         	|or
	         	|procedure
	         	|routine
	         	|switch
	         	|then|to|type
	         	|until
	         	|while
	         	|xor
         	)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.jump.euphoria</string>
                <key>match</key>
                <string>\b(abort|break|continue|crash|entry|exit|fallthru|goto|label|return|retry)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.type.euphoria</string>
                <key>match</key>
                <string>\b(object|sequence|integer|atom)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.modifier.access-control.euphoria</string>
                <key>match</key>
                <string>\b(override|global|public|export)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.euphoria</string>
                <key>match</key>
                <string>\b[A-Z0-9_]+\b</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"""</string>
                <key>name</key>
                <string>string.quoted.triple.euphoria</string>
                <key>end</key>
                <string>"""</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>`</string>
                <key>name</key>
                <string>string.quoted.backtick.euphoria</string>
                <key>end</key>
                <string>`</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.euphoria</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.euphoria</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                </array>
                <key>end</key>
                <string>"</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.euphoria</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.single.euphoria</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string_escaped_char</string>
                    </dict>
                </array>
                <key>end</key>
                <string>'</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>\s*--\*\*</string>
                <key>name</key>
                <string>comment.line.eudoc.euphoria</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.documentation.section.eudoc.euphoria</string>
                        <key>match</key>
                        <string>[A-Za-z0-9\s]+:\s*$</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.documentation.bold.eudoc.euphoria</string>
                        <key>match</key>
                        <string>\*\*[^*]+\*\*</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.documentation.fixed.eudoc.euphoria</string>
                        <key>match</key>
                        <string>\#\#[^*]+\#\#</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>\[\[</string>
                        <key>name</key>
                        <string>keyword.other.documentation.link.eudoc.euphoria</string>
                        <key>end</key>
                        <string>\]\]</string>
                    </dict>
                </array>
                <key>end</key>
                <string>^\s*[^-]</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>/\*</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>comment.block.euphoria</string>
                <key>end</key>
                <string>\*/</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.euphoria</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>comment.line.double-dash.euphoria</string>
                <key>match</key>
                <string>(--).*$\n?</string>
            </dict>
        </array>
        <key>name</key>
        <string>Euphoria</string>
        <key>scopeName</key>
        <string>source.euphoria</string>
        <key>fileTypes</key>
        <array>
            <string>e</string>
            <string>ex</string>
            <string>exw</string>
            <string>exu</string>
        </array>
        <key>repository</key>
        <dict>
            <key>string_escaped_char</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.euphoria</string>
                        <key>match</key>
                        <string>\\(\\|[nrte'"0?]|[0-3]\d{2}|[4-7]\d?|x[a-fA-F0-9]{2}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|b[0-1]+)</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>invalid.illegal.unknown-escape.euphoria</string>
                        <key>match</key>
                        <string>\\.</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>firstLineMatch</key>
        <string>^#!/.*\beui(w)?\b</string>
    </dict>
</plist>
